GET http://localhost:3000/products/1


###
POST http://localhost:3000/products
Content-Type: application/json

{
    "id": "baaaa",
    "name": "dumama",
    "description": "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    "price": 100,
    "image": [
        "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lwxoz5gn0bmjbd.webp", 
        "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lwxoz5gn5xwb6f.webp",
        "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lvmt7gpmhfkh91.webp"
    ],
    "category": "Women",
    "subCategory": "Topwear",
    "sizes": ["S", "M", "L"],
    "date": 1716634345448,
    "bestseller": true
}


###
DELETE http://localhost:3000/products/baaaa