server:
    port: ${PORT:8080}

spring:
    config:
        import: optional:file:.env
    datasource:
        url: ${SPRING_DATASOURCE_URL}
        driverClassName: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: ${DDL_AUTO:validate}
        show-sql: false
        open-in-view: false
    servlet:
        multipart:
            max-file-size: ${MAX_FILE_SIZE:10MB}
    web:
        resources:
            add-mappings: true
jwt:
    signerKey: ${JWT_SIGNER_KEY}
    valid-duration: 3600 # in second
    refreshable-duration: 36000 # in seconds

firebase:
    config:
        path: ${FIREBASE_CONFIG_PATH}

cloudinary:
    cloud_name: ${CLOUDINARY_CLOUD_NAME}
    api_key: ${CLOUDINARY_API_KEY}
    api_secret: ${CLOUDINARY_API_SECRET}
payment:
    zalo:
        app-id: ${ZALO_APP_ID}
        secret-key: ${ZALO_SECRET_KEY}
        public-key: ${ZALO_PUBLIC_KEY}
        endpoint: ${ZALO_ENDPOINT}
        callback-url: ${ZALO_CALLBACK}
        redirect-url: ${ZALO_REDIRECT:"https://hcmut-e-commerce.vercel.app/orders"}


security:
    cors:
        allowed-origins: ${CORS_ALLOWED_ORIGINS}
        allowed-methods: ${CORS_ALLOWED_METHODS:*}
        allowed-headers: ${CORS_ALLOWED_HEADERS:*}

openapi:
    service:
        api-docs: ${OPENAPI_SERVICE_API_DOCS}
        title: ${OPENAPI_SERVICE_TITLE}
        version: ${OPENAPI_SERVICE_VERSION}
        server: ${OPENAPI_SERVICE_SERVER}
springdoc:
    swagger-ui:
        path: ${SWAGGER_UI_PATH:/docs}
