server:
    port: 8080

spring:
    config:
        import: optional:file:.env
    datasource:
        url: ${SPRING_DATASOURCE_URL}
        driverClassName: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
        open-in-view: false

jwt:
    signerKey: ${JWT_SIGNER_KEY}
    valid-duration: 3600 # in second
    refreshable-duration: 36000 # in seconds

firebase:
    config:
        path: ${FIREBASE_CONFIG_PATH}

payment:
    zalo:
        app-id: ${ZALO_APP_ID}
        secret-key: ${ZALO_SECRET_KEY}
        public-key: ${ZALO_PUBLIC_KEY}
        endpoint: ${ZALO_ENDPOINT}
