server:
    port: 8080

spring:
    config:
        import: optional:file:.env
    datasource:
        url: "jdbc:mysql://localhost:3306/ecommerce"
        driverClassName: "com.mysql.cj.jdbc.Driver"
        username: root
        password: Chinhtran5504
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        open-in-view: false

jwt:
    signerKey: "-Lo6pGNIOrFouISapR74-s_BkjNLrHu3hq5SGnstXmvrZeDWzIAdcNRYIGWxUV6cygjL2euOfONvfKXdFZ4tEw"
    valid-duration: 3600 # in second
    refreshable-duration: 36000 # in secondss